AWSTemplateFormatVersion: '2010-09-09'
Description: Main stack for network resources (VPC, Subnets, SGs)

Parameters:
  PJCode:
    Type: String
    Default: MakeNetwork

Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://S3バケット名.s3.amazonaws.com/projects/フォルダ名/vpc.yaml
      Parameters:
        PJCode: !Ref PJCode

  SGStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://S3バケット名.s3.amazonaws.com/projects/フォルダ名/sg.yaml
      Parameters:
        PJCode: !Ref PJCode
