# cloudformationのバージョン指定
AWSTemplateFormatVersion: 2010-09-09

# テンプレートに対する説明
Description: ---

# スタック作成時の値をカスタム
Parameters:
  ProjectName:
    Type: string
    Default: cfn-

# リソースの種類の記述
Resources:
  Type: AWS::EC2::VPC

  # リソースに対する設定
  Properties:
  
    # VPCのcider
    CidrBlock: 10.0.0.0/16

    # このVPC内で起動したインスタンスがホスト名を取得するかどうかを示す
    EnableDnsSupport: true

    # VPCのタグキーの設定
    Tags:
      - Key: Name
        Value: !Sub ${ProjectName} VPC